### ISSUE TITLE
MP Export Test Automation(Workspace/Logged in) v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#147]
## Context 
Scope:  **This ticket is to create a test script to automate the UI functionality for export** 

Create a test script to Export a MP for the logged in view 

Utilize the following: Facility:  Gadsden, 1,2, CS0BAN

Export Logged in view API endpoint: 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b957d185-c4a1-4bda-b8e0-d2c59c717b7f)
https://api.epa.gov/easey/dev/monitor-plan-mgmt/swagger/#/Plans/MonitorPlanController_exportMonitorPlan

**Comment by mackenzieharwood** [comment]
Just need to add credentials to env properties and it _should_ work

**Comment by mackenzieharwood** [comment]
Credentials are added, retrieved, and stored. Can't log in with my credentials - manually. Investigating password reset?

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/214
PR link
*note: log in system is cases sensitive*
