### ISSUE TITLE
QA (Test Data, Cert, TEE)  Import From File Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#148]
## Context 
One test script to import all QA test types:

 Note: The scope of this ticket is for QA test data, Cert data, and TEE data

1. Export a QA file 
2. Log in to ECMPS 
3. Check out a config 
4. Select Import 
5. Select import from file 
6.  Import the QA file

The system displays a success message 

 

Import for years 2020 and up

**Comment by mackenzieharwood** [comment]
Test Data
https://github.com/US-EPA-CAMD/easey-testing/pull/278/

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/279
TEE ---- needs file update to upload.json as well
