### ISSUE TITLE
QA Export Test Automation (Global/Non-logged in) v1.0 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#149]
## Context 
Scope:  **This ticket is to create a test script to automate the UI functionality for export** 

A test script to export a QA file from the global view (non logged in) 

Use the following faclity: Gadsden 2015 Q1

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/96725abf-b9c3-4e2c-8f78-bdd8ea10aa9e)
https://api.epa.gov/easey/dev/qa-certification-mgmt/swagger/#/QA%20Certification/QACertificationController_export

**Comment by mackenzieharwood** [comment]
moved common methods from mp export test to commonExport file - Still modifying methods to pass only the locators that have name changes between local & global to make it as modular as possible for future work

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/215

Wrapped up - still somethings I need to rework in the future for all export tests:
-username in file download path
-wait times
-file name matcher sensitive - returns false if downloaded multiple times
