### ISSUE TITLE
MP Defaults Test Automation v1.0 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#153]
## Context 

Create one script that complete the following actions for MP defaults: Create, Edit, Evaluate, Revert to Offical Record 

- would like some clarification from the EPA on if every field in the create modal should be filled out 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0eb01910-f24c-4117-9ba6-9cf2c720c1c2)

**Comment by mosesdeeCVP** [comment]
Test Complete
