### ISSUE TITLE
MP Formulas Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#155]
## Context 
Create one script that complete the following actions for MP Formulas: Create, Edit, Evaluate, Revert to Offical Record

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/1e71017b-9b03-4032-89ed-8d0abb156a5d)

**Comment by mosesdeeCVP** [comment]
Test Complete
