### ISSUE TITLE
MP Loads Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#156]
## Context 

Create one script that complete the following actions for MP Loads  Create, Edit, Evaluate, Revert to Offical Record

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ac31ee2c-7d3c-4119-b05c-8c1569058824)

**Comment by mosesdeeCVP** [comment]
Automated Test Complete
