### ISSUE TITLE
MP Recantgular Duct WAFs

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#160]
## Context 
Create one script that complete the following actions for MP WAFs rectangular duct 
Create, Edit, Evaluate, Revert to Offical Record

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/38520e30-1a3d-43df-8580-240faba63c73)

**Comment by mosesdeeCVP** [comment]
Work Completed
