### ISSUE TITLE
MP Spans Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#161]
## Context

Create one script that complete the following actions for MP spans 
Create, Edit, Evaluate, Revert to Offical Record

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c1b22c60-897f-4039-b328-76587bcfc5ef)

**Comment by mosesdeeCVP** [comment]
Work Complete
