### ISSUE TITLE
MP Unit Fuels Information Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#163]
## Context 
Create one script that complete the following actions for unit fuels, 
 Create. Edit, Evaluate, Revert to offical record 

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/6d5d451b-b433-4109-941c-e41ef7875f8f)

**Comment by mosesdeeCVP** [comment]
Test Complete
