### ISSUE TITLE
MP Supplemental Methods Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#171]
## Context 
Create one script that completes the following actions for supplemental methods: Create, Edit, Evaluate, Revert to Offical Record

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/fe00b189-7efa-4a84-9da1-c3631a83f9d9)

**Comment by mosesdeeCVP** [comment]
Test has been created
