### ISSUE TITLE
MP Unit Control Test Automation v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#178]
## Context 

Create one script that complete the following actions for unit control
Create. Edit, Evaluate, Revert to offical record

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/c03a84ac-f702-40a6-be0f-91333c1a8ac0)

**Comment by mosesdeeCVP** [comment]
Test Created
