### ISSUE TITLE
MP Export Test Automation (Global view) v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#191]
## Context 

Scope:  **This ticket is to create a test script to automate the UI functionality for export** 

Create a test script to Export a MP for the Global view (non Logged in)

Utilize the following: Facility: Gadsden, 1,2, CS0BAN

Below is the export endpoint for MP,
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/baf57eb8-a872-435d-9f52-2799c671747f)
https://api.epa.gov/easey/dev/monitor-plan-mgmt/swagger/#/Plans/MonitorPlanController_exportMonitorPlan

**Comment by mackenzieharwood** [comment]
Working on branch MPExportGlobalTest
https://github.com/US-EPA-CAMD/easey-testing/tree/MPExportGlobalTest

**Comment by mackenzieharwood** [comment]
All selections are able to be made, export button is pressed.
Next: validate download pop up at bottom of window

**Comment by mackenzieharwood** [comment]
Facility is selected, goes to export page, validates export title, selects all to download, clicks download
Troubleshooting method to validate download

**Comment by mackenzieharwood** [comment]
Traverses through downloads folder but uses my name folder path(need to replace with something generic). Also need to fix regex for assert statement.
Sample Output:
![image.png](https://images.zenhubusercontent.com/6384e8c859b5664af107c1a0/12157f38-f69c-4b44-a3f1-86c846102e70)

**Comment by mackenzieharwood** [comment]
Implemented method to set chrome download path to src folder; currently no files get downloaded into it- looking into possible wait time issues or file path issues

**Comment by JanellC** [comment]
Ticket completed
