### ISSUE TITLE
QA Export Test Automation (Workspce/logged in) v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#192]
## Context 
Scope:  **This ticket is to create a test script to automate the UI functionality for export** 

A test script to export a QA file from the global view (workspace/ logged in) 

Use the following faclity: Gadsden 2015 Q1

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/b27536aa-73be-4164-a370-a33df9ae168a)

https://api.epa.gov/easey/dev/qa-certification-mgmt/swagger/#/QA%20Certification/QACertificationWorkspaceController_export

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/216
