### ISSUE TITLE
Lineraity Workspace Smoke Test

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#220]
## Context 

-navigate to QA in workspace
-Select a configuration
- Select lineraity as a test type 
- check out a configration 
- Add a lineraity test record 
- View the added the record in the view modal 
- Revert to offical record (Must revert in the Monitoring Plan module)

**Comment by mackenzieharwood** [comment]
Passing date to calendar selection is preventing "submit" button from being pressed.

**Comment by mackenzieharwood** [comment]
date passed like this : mm/dd/yyyy with "/" included

Submit button pressed and all selections get erased

**Comment by mackenzieharwood** [comment]
Submit button still not working as expected

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/228/

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/234/
