### ISSUE TITLE
Rata Workspace Smoke Test v1.0

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#222]
## Context 

navigate to QA in workspace
Select a configuration
Select rata as a test type 
check out a configration 
Add a  Rata data record 
View the added the record in the view modal 
Revert to offical record (Must revert in the Monitoring Plan module)

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/262
