### ISSUE TITLE
Update MP export Documentation for Automated Test 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/easey-testing#273]
## Context 

Create a export script for All MP sections located in the UI dropdown . There will be multiple file downloads from the script

**Comment by mackenzieharwood** [comment]
"All sections" dropdown screenshot
![image.png](https://images.zenhubusercontent.com/6384e8c859b5664af107c1a0/2cc88c95-48a1-4be9-81b2-c2fafb0493f7)

**Comment by mackenzieharwood** [comment]
https://github.com/US-EPA-CAMD/easey-testing/pull/274

Both global and local test to export all files from "sections" dropdown shown above. This PR also includes changes to the ReadME regarding versioning.
